# server:
#   port: 0101

logging:
  level:
    "[org.hibernate.sql]": debug
  file:
    path: logs

spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: dev

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true