spring:
  profiles:
    active: dev
  security:
    user:
      name: user
      password: password
  # jackson:
  #   default-property-inclusion: NON_NULL

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true